# Generated by Django 4.0.1 on 2022-06-07 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id_action', models.AutoField(primary_key=True, serialize=False)),
                ('action_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id_day', models.AutoField(primary_key=True, serialize=False)),
                ('day_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Lock',
            fields=[
                ('id_lock', models.AutoField(primary_key=True, serialize=False)),
                ('lock_name', models.CharField(max_length=30)),
                ('lock_mac', models.CharField(max_length=30)),
                ('auto_lock_time', models.IntegerField()),
                ('lock_data', models.CharField(max_length=5000)),
                ('lock_status', models.CharField(max_length=30)),
                ('lock_percent', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id_role', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Passage_mode',
            fields=[
                ('id_passage_mode', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField(max_length=30)),
                ('end_date', models.DateTimeField(max_length=30)),
                ('status', models.CharField(max_length=30)),
                ('locks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.lock')),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.IntegerField()),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.role')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='lock',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.myuser'),
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.action')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.day')),
            ],
        ),
        migrations.CreateModel(
            name='FingerPrint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerPrint', models.CharField(max_length=30, null=True)),
                ('description', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField(max_length=30)),
                ('end_date', models.DateTimeField(max_length=30)),
                ('is_set', models.IntegerField(default='0')),
                ('lock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.lock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.myuser')),
            ],
        ),
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, null=True)),
                ('description', models.CharField(max_length=30)),
                ('start_date', models.DateTimeField(max_length=30)),
                ('end_date', models.DateTimeField(max_length=30)),
                ('is_set', models.IntegerField(default='0')),
                ('lock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.lock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.myuser')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.CharField(max_length=30, null=True)),
                ('description', models.CharField(max_length=30)),
                ('start_date', models.DateTimeField(max_length=30)),
                ('end_date', models.DateTimeField(max_length=30)),
                ('is_set', models.IntegerField(default='0')),
                ('lock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.lock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.myuser')),
            ],
        ),
        migrations.CreateModel(
            name='Bluetooth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=30)),
                ('start_date', models.DateTimeField(max_length=30)),
                ('end_date', models.DateTimeField(max_length=30)),
                ('is_set', models.IntegerField(default='0')),
                ('lock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.lock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.myuser')),
            ],
        ),
        migrations.CreateModel(
            name='Associate_passage_mode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.day')),
                ('passage_mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.passage_mode')),
            ],
        ),
        migrations.AddField(
            model_name='action',
            name='lock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.lock'),
        ),
        migrations.AddField(
            model_name='action',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.myuser'),
        ),
    ]
