# Generated by Django 4.0.1 on 2022-05-24 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Acces',
            fields=[
                ('id_acces', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=30)),
                ('start_time', models.DateTimeField(max_length=30, null=True)),
                ('end_time', models.DateTimeField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id_action', models.AutoField(primary_key=True, serialize=False)),
                ('action_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id_category', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id_day', models.AutoField(primary_key=True, serialize=False)),
                ('day_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Lock',
            fields=[
                ('id_lock', models.AutoField(primary_key=True, serialize=False)),
                ('lock_name', models.CharField(max_length=30)),
                ('lock_mac', models.IntegerField()),
                ('auto_lock_time', models.IntegerField()),
                ('lock_data', models.IntegerField()),
                ('lock_status', models.IntegerField()),
                ('lock_percent', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id_role', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id_room', models.AutoField(primary_key=True, serialize=False)),
                ('room_name', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id_product', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('subtitle', models.TextField(max_length=30, null=True)),
                ('description', models.TextField(max_length=30, null=True)),
                ('price', models.IntegerField()),
                ('image', models.FileField(upload_to='Images')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.category')),
            ],
        ),
        migrations.CreateModel(
            name='Passage_mode',
            fields=[
                ('id_passage_mode', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(max_length=30)),
                ('end_time', models.DateTimeField(max_length=30)),
                ('status', models.CharField(max_length=30)),
                ('locks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.lock')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_date', models.DateField()),
                ('quality', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.myuser')),
            ],
        ),
        migrations.AddField(
            model_name='myuser',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.role'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lock',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.room'),
        ),
        migrations.AddField(
            model_name='lock',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.myuser'),
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.action')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.day')),
            ],
        ),
        migrations.CreateModel(
            name='Associate_passage_mode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.day')),
                ('passage_mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.passage_mode')),
            ],
        ),
        migrations.AddField(
            model_name='action',
            name='lock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.lock'),
        ),
        migrations.AddField(
            model_name='action',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.myuser'),
        ),
        migrations.CreateModel(
            name='Acces_fingerPrint',
            fields=[
                ('id_acces_fingerPrint', models.AutoField(primary_key=True, serialize=False)),
                ('fingerPrint_name', models.CharField(max_length=30)),
                ('fingerPrint_number', models.IntegerField()),
                ('acces', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.acces')),
            ],
        ),
        migrations.CreateModel(
            name='Acces_code',
            fields=[
                ('id_acces_code', models.AutoField(primary_key=True, serialize=False)),
                ('code_name', models.CharField(max_length=30)),
                ('code_number', models.IntegerField()),
                ('acces', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.acces')),
            ],
        ),
        migrations.CreateModel(
            name='Acces_card',
            fields=[
                ('id_acces_card', models.AutoField(primary_key=True, serialize=False)),
                ('card_name', models.CharField(max_length=30)),
                ('card_number', models.IntegerField()),
                ('acces', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.acces')),
            ],
        ),
        migrations.AddField(
            model_name='acces',
            name='locks',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.lock'),
        ),
        migrations.AddField(
            model_name='acces',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.myuser'),
        ),
    ]
