# Generated by Django 4.0.1 on 2022-06-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lock',
            name='room',
        ),
        migrations.AlterField(
            model_name='bluetooth',
            name='is_set',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='card',
            name='card',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='is_set',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='code',
            name='code',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='code',
            name='is_set',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='fingerprint',
            name='fingerPrint',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='fingerprint',
            name='is_set',
            field=models.IntegerField(default='0'),
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
