# Generated by Django 4.0.1 on 2022-06-14 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_myuser_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='backend/assets/img/user.png', upload_to='profile_images')),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='store.myuser')),
            ],
        ),
    ]
