# Generated by Django 4.0.1 on 2022-06-14 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='staff',
            new_name='myuser',
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='backend/assets/img/user.png', null=True, upload_to='profile_images'),
        ),
    ]
