# Generated by Django 4.0.1 on 2022-06-14 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_staff_profile_myuser_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='backend/assets/img/user.png', upload_to='profile_images'),
        ),
    ]
