# Generated by Django 4.0.1 on 2022-06-14 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='image',
            field=models.ImageField(default='backend/assets/img/user.png', upload_to='profile_images'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
