# Generated by Django 4.0.1 on 2022-06-14 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_myuser_image_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='image',
            field=models.ImageField(default='default.png', upload_to='profile_images'),
        ),
    ]
